# Generated by Django 4.0.2 on 2022-04-13 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myvideos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
    ]
