# Generated by Django 4.0.2 on 2022-04-14 22:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myvideos', '0003_eventgallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventgallery',
            name='event_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Event Date'),
        ),
    ]
