# Generated by Django 3.2.3 on 2022-04-20 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myvideos', '0007_rename_event_eventgallery_eventname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventgallery',
            name='event_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d'),
        ),
    ]
