# Generated by Django 3.2.3 on 2022-04-29 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myvideos', '0008_alter_eventgallery_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventgallery',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comment'),
        ),
    ]
